### ISSUE TITLE
Vrms values, power supply

### ISSUE THREAD

**Issue by ArashiCZ** [openenergymonitor/emontx3#4]
Hello,

My emonTX3 with emonESP measures 260 Vrms AC.
I live in Czech republic, therefor grig voltages are  230V AC 1 phase and 400V AC 3 phase.

My expensive True RMS multimmeter measures 232,6 V AC.
I'm using 9V AC-AC Europe adapter, that I boughtt with the device.

Could it be caused by I'm having to use second power supply, beacuse the EmonESP doesn't work with 9V AC adaptor only?

Thank you.

**Comment by glynhudson** [comment]
Hi, 

You you need to calibrate for the specific AC-AC voltage adaptor you are using. The error is not caused by the two power supplies. You should ensure jumper JP2 is removed when using the two power supplies. See calibration procedure: https://learn.openenergymonitor.org/electricity-monitoring/ctac/calibration

You need to edit `Vcal`: 

https://github.com/openenergymonitor/emontx3/blob/master/firmware/src/src.ino#L98
